apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrnets.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Cluster
  names:
    plural: kuryrnets
    singular: kuryrnet
    kind: KuryrNet
    shortNames:
    - kn
---
apiVersion: "openstack.org/v1"
kind: KuryrNet
metadata:
  name: cluster1
spec:
  ovs_bridge: br-int
  pod_security_groups: id_of_secuirity_group_for_pods
  pod_subnet: id_of_subnet_for_pods
  project: id_of_project
  service_subnet: id_of_subnet_for_k8s_services